Repository vegastrike/Assets-Production, pull requests merged in 2021-12, with the labels that each got.

#83 Enhancement: Display Engine Version Information
  modules/GUI.py
Labels: enhancement

#84 GH Actions - PR, Release: Add Fedora 35, Omit Fedora 33 (0.8.x)
  .github/workflows/gh-actions-pr.yml
  .github/workflows/gh-actions-release.yml
Labels: enhancement, CI/CD

#85 Last minute CMake stuff on 0.8.x
  .github/workflows/codeql.yml
  CMakeLists.txt
  FindLinuxDistro.cmake
Labels: CI/CD

#86 Port last minute CMake stuff to master
  .github/workflows/codeql.yml
  .github/workflows/gh-actions-pr.yml
  .github/workflows/gh-actions-release.yml
  CMakeLists.txt
  FindLinuxDistro.cmake
  script/cibuild
Labels: CI/CD

#87 script/cibuild: Forward GITHUB_SHA env variable
  script/cibuild
Labels: CI/CD
