Repository vegastrike/Assets-Production, pull requests merged in 2021-01, with the labels that each got.

#44 Migration: GitHub Actions
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .github/workflows/codeql.yml
  .github/workflows/fortify-on-demand-scan.yml
  .github/workflows/gh-actions-pr.yml
  .github/workflows/gh-actions-release.yml
Labels: CI/CD, enhancement

#45 Migration: Drop Support for Travis-CI
  .travis.yml
Labels: enhancement

#46 Migration 0.7.x gh actions
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .github/workflows/codeql.yml
  .github/workflows/fortify-on-demand-scan.yml
  .github/workflows/gh-actions-pr.yml
  .github/workflows/gh-actions-release.yml
  .travis.yml
Labels: CI/CD, enhancement

#47 Migration: Artifacts for Release builds
  .github/workflows/gh-actions-release.yml
Labels: CI/CD, enhancement

#48 CMakeLists.txt, script/[cibuild,docker-entrypoint.sh]: Adj to GH Actions
  CMakeLists.txt
  script/cibuild
  script/docker-entrypoint.sh
Labels: CI/CD
